skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_escrow = "CHH7Z21D9ZRG1iy5Wb9A96SEMWaGmzLXYkGZwwN7z23f"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
